---

- name: Placeholder for /etc/environment
  copy:
    src: etc/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set /etc/profile
  template:
    src: etc/profile.j2
    dest: /etc/profile
    owner: root
    group: root
    mode: '0644'
    backup: yes
