---

- name: Check -march support
  shell: |
    /lib/ld-linux-x86-64.so.2 --help | grep supported|xargs|awk '{print $1}'
  register: supported_march
  tags: ["always"]
  check_mode: False

- block:
    - name: Set architecture
      set_fact:
        architecture: "x86-64-v3"
      when: supported_march.stdout_lines[0] == 'x86-64-v3'

    - name: Set architecture
      set_fact:
        architecture: "x86-64"
      when: supported_march.stdout_lines[0] == 'x86-64-v2'

  when: supported_march.stdout_lines[0] is defined
  tags: ["always"]
  check_mode: False
