---
- name: Networking Tasks
  ansible.builtin.debug:
    msg: "Starting networking tasks"

- tags:
  - firewall
  ansible.builtin.import_tasks:
    file: firewall.yml

# https://gitlab.com/klaasjan/vagrant-ansible/-/blob/master/ansible/roles/configure_network/tasks/main.yml?ref_type=heads

# - name: Setup udev for network devices
#   replace:
#     dest: /etc/udev/rules.d/10-network.rules
#     regexp: 'ATTR.*{{ item.ifname }}'
#     replace: 'ATTR{address}=="{{ item.mac|lower }}", ATTR{type}=="1", NAME="{{ item.ifname }}'
#   with_items: "{{ network_interfaces }}"
#   when: network_interfaces is defined
#   notify: Reload udev rules

#TODO: convert to systemd-networkd
# - import_tasks:
#     file: networkmanager.yml
#   tags: ['networkmanager']

- tags:
  - ntp
  ansible.builtin.import_tasks:
    file: ntp.yml

# TODO: set interface config for .36 network cards betweeen soundbot|ninjabot
# - include_tasks: interfaces.yml

- name: Set hosts files
  when: etc_hosts is defined
  tags:
  - dns
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: true
