---

- name: Check if systemd-timesyncd service exists
  register: timesyncd_service
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/systemd-timesyncd.service

- block:
  - name: Create timesyncd.conf.d directory
    ansible.builtin.file:
      path: /etc/systemd/timesyncd.conf.d
      state: directory

  - name: set ntp servers in timesyncd.conf
    register: timesyncd_conf
    notify: enable systemd-timesyncd service
    ansible.builtin.copy:
      src: etc/systemd/timesyncd.conf.d/local.conf
      dest: /etc/systemd/timesyncd.conf.d/local.conf
      mode: '0644'
      backup: true

  - name: Sync hwclock
    shell: |
      timedatectl set-ntp true && \
      sleep 4 && \
      hwclock --systohc
    when:
      - timesyncd_conf.changed
      - ansible_distribution != 'Debian'
  when: timesyncd_service.stat.exists
