---

- name: Create the directories for site specific configurations
  with_items:
  - sites-available
  - sites-enabled
  - auth_basic
  - conf.d
  - conf.d/stream
  tags:
  - configuration
  - nginx
  ansible.builtin.file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: root
    group: nginx
    mode: '0755'
    recurse: false

- name: Ensure log directory exist
  tags:
  - configuration
  - nginx
  ansible.builtin.file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: nginx
    group: nginx
    recurse: false
