---

- when: use_ssl is defined
  tags:
  - ssl
  ansible.builtin.include_tasks: tasks/ssl.yml

- name: copy rsyslog config for nginx
  notify: restart rsyslog
  tags:
  - configuration
  - nginx
  ansible.builtin.copy:
    src: 90-nginx_rsyslog.conf
    dest: /etc/rsyslog.d/90-nginx_rsyslog.conf
    owner: root
    group: root
    mode: '0644'

- when: nginx_official_repo == True
  ansible.builtin.import_tasks:
    file: nginx-official-repo.yml

- when: nginx_passenger == True
  ansible.builtin.import_tasks:
    file: passenger-phusion-repo.yml

- when: nginx_installation_type == "packages"
  ansible.builtin.import_tasks:
    file: installation.packages.yml

- when: nginx_installation_type == "source"
  ansible.builtin.import_tasks:
    file: installation.source.yml

- ansible.builtin.import_tasks:
    file: ensure-dirs.yml

- when: not keep_only_specified
  ansible.builtin.import_tasks:
    file: remove-defaults.yml

- when: keep_only_specified
  ansible.builtin.import_tasks:
    file: remove-extras.yml

- ansible.builtin.import_tasks:
    file: remove-unwanted.yml

- ansible.builtin.import_tasks:
    file: configuration.yml

- name: Create /usr/share/nginx/html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    owner: root
    group: root
    recurse: true

- name: create blank index.html for default traffic
  when: nginx_create_blank_index
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    backup: true
    owner: root
    group: root
    mode: '0644'

- ansible.builtin.import_tasks:
    file: selinux.yml

- name: Start the nginx service
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
  tags:
  - service
  - nginx
  ansible.builtin.service:
    name: '{{ nginx_service_name }}'
    state: started
    enabled: true
