---
- name: Find enabled sites
  register: enabled_sites
  changed_when: false
  tags:
  - configuration
  - nginx
  ansible.builtin.shell: ls -1 {{nginx_conf_dir}}/sites-enabled || true

- name: Disable unmanaged sites
  with_items: "{{ enabled_sites.stdout.split() }}"
  # 'item.conf' => 'item'
  when: item[:-5] not in nginx_sites.keys()
  notify:
  - reload nginx
  tags:
  - configuration
  - nginx
  ansible.builtin.file:
    path: '{{nginx_conf_dir}}/sites-enabled/{{ item }}'
    state: absent

- name: Find config files
  register: config_files
  changed_when: false
  tags:
  - configuration
  - nginx
  ansible.builtin.shell: ls -1 {{nginx_conf_dir}}/conf.d

- name: Remove unmanaged config files
  with_items: "{{ config_files.stdout.split() }}"
  # 'item.conf' => 'item'
  when: item[:-5] not in nginx_configs.keys()
  notify:
  - reload nginx
  tags:
  - configuration
  - nginx
  ansible.builtin.file:
    name: '{{nginx_conf_dir}}/conf.d/{{ item }}'
    state: absent
