---

- name: Install i3 packages
  block:
    - name: Install i3 packages from official repositories
      package:
        name: "{{ i3_packages[ansible_distribution | lower] }}"
        state: present

    - name: Install i3status-rust on Fedora
      block:
        - name: Clone i3status-rust repository
          git:
            repo: 'https://github.com/greshake/i3status-rust.git'
            dest: /tmp/i3status-rust

        - name: Build and install i3status-rust
          command:
            cmd: cargo install --path .
            chdir: /tmp/i3status-rust
          environment:
            PATH: "{{ ansible_env.PATH }}:/usr/local/cargo/bin"

      when: ansible_distribution == 'Fedora'
