---

- block:
    - name: install packages
      aur:
        use: paru
        name: sonic-pi-git
        state: present
        extra_args: "--overwrite '*'"
      become: False
      tags: ['packages']

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a sonic-pi-git. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False
  tags: ['packages']
