---
# handlers file for pipewire

- name: Restart PipeWire
  systemd:
    name: pipewire
    state: restarted
    scope: user

- name: Restart WirePlumber
  systemd:
    name: wireplumber
    state: restarted
    scope: user
