---

#TODO: 
# 
# https://github.com/hyperupcall/autoenv.git

- name: Set user shell
  with_items:
  - '{{ user.name }}'
  tags:
  - profile
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ user.shell }}"

- name: Set user aliases
  tags:
  - aliases
  - profile
  ansible.builtin.template:
    src: .aliases.j2
    dest: "{{ user.home }}/.aliases"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: true

- when: user.shell == "/usr/bin/bash"
  tags:
  - bash
  - profile
  ansible.builtin.import_tasks:
    file: bash.yml

- when: user.shell == "/usr/bin/zsh"
  tags:
  - zsh
  - profile
  ansible.builtin.import_tasks:
    file: zsh.yml
