---
# tasks file for shell

- import_tasks:
    file: zsh.yml
  tags: ['zsh', 'profile']

- name: Set user shell
  user:
    name: "{{ item }}"
    shell: "{{ user.shell }}"
  with_items:
    - "{{ user.name }}"
    # - root
  tags: ['profile']

- name: Set user aliases
  template:
    src: .aliases.j2
    dest: "{{ user.home }}/.aliases"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: true
  tags: ['aliases', 'profile']
