# Gemfile

source 'https://rubygems.org'

gem 'cli-ui'
gem 'debug', '1.8.0'
gem 'google-protobuf', '3.25.0'
gem 'io-console', '0.6.0'
gem 'irb', '1.8.3'
gem 'parseconfig'
gem 'pry'
gem 'pry-doc'
gem 'psych', '5.1.1.1'
gem 'rake'
gem 'rdoc', '6.5.0'
gem 'reline', '0.3.9'
gem 'rubocop'
gem 'sorbet-runtime', '0.5.11116'
gem 'stringio', '3.0.8'
gem 'tty-progressbar'
