authors:
- Robert Pannick <rwpannick@gmail.com>
dependencies: {}
description: Storage management roles
license:
- MIT
name: storage
namespace: b08x
readme: README.md
repository: https://github.com/b08x/ansible-collections
tags:
- storage
version: 1.0.0
