---

- include_tasks: tasks/ssl.yml
  when: use_ssl is defined
  tags: ['ssl']

- name: copy rsyslog config for nginx
  copy: >
    src=90-nginx_rsyslog.conf
    dest=/etc/rsyslog.d/90-nginx_rsyslog.conf
    owner=root
    group=root
    mode=0644
  notify: restart rsyslog
  tags: [configuration,nginx]

- import_tasks:
    file: nginx-official-repo.yml
  when: nginx_official_repo == True

- import_tasks:
    file: passenger-phusion-repo.yml
  when: nginx_passenger == True

- import_tasks:
    file: installation.packages.yml
  when: nginx_installation_type == "packages"

- import_tasks:
    file: installation.source.yml
  when: nginx_installation_type == "source"

- import_tasks:
    file: ensure-dirs.yml

- import_tasks:
    file: remove-defaults.yml
  when: not keep_only_specified

- import_tasks:
    file: remove-extras.yml
  when: keep_only_specified

- import_tasks:
    file: remove-unwanted.yml

- import_tasks:
    file: configuration.yml

- name: Create /usr/share/nginx/html
  file:
    path: /usr/share/nginx/html
    state: directory
    owner: root
    group: root
    recurse: True

- name: create blank index.html for default traffic
  copy: >
    src=index.html
    dest=/usr/share/nginx/html/index.html
    backup=yes
    owner=root
    group=root
    mode=0644
  when: nginx_create_blank_index

- import_tasks:
    file: selinux.yml

- name: Start the nginx service
  service: name={{ nginx_service_name }} state=started enabled=yes
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
  tags: [service,nginx]
