---
# tasks file for ide

- name: Load distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install VSCode repository key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add VSCode repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  when: ansible_os_family == "Debian"

- name: Install VSCode (Debian/Ubuntu)
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Import Microsoft GPG key (RedHat)
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == "RedHat"

- name: Add VSCode repository (RedHat)
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == "RedHat"

- name: Install VSCode (RedHat)
  ansible.builtin.dnf:
    name: code
    state: present
  when: ansible_os_family == "RedHat"

- name: Install VSCode (Arch Linux)
  community.general.pacman:
    name: visual-studio-code-bin
    state: present
  when: ansible_distribution == "Archlinux"

- name: Download Pulsar AppImage
  ansible.builtin.get_url:
    url: "https://github.com/pulsar-edit/pulsar/releases/latest/download/Linux.Pulsar.AppImage"
    dest: "/usr/local/bin/pulsar"
    mode: '0755'
  become: true

- name: Create Pulsar desktop entry
  ansible.builtin.copy:
    dest: "/usr/share/applications/pulsar.desktop"
    content: |
      [Desktop Entry]
      Name=Pulsar
      Comment=A Community-led Hyper-Hackable Text Editor
      GenericName=Text Editor
      Exec=/usr/local/bin/pulsar %F
      Icon=pulsar
      Type=Application
      StartupNotify=true
      Categories=TextEditor;Development;
      MimeType=text/plain;
    mode: '0644'
  become: true

- name: Download Pulsar icon
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/pulsar-edit/pulsar/master/resources/app/resources/icons/1024x1024.png"
    dest: "/usr/share/icons/hicolor/1024x1024/apps/pulsar.png"
    mode: '0644'
  become: true
