---

- name: Ensure /usr/local/share fonts exists
  file:
    path: /usr/local/share/fonts
    state: directory
    owner: root
    group: root
    recurse: True
  register: fontsdir

- name: Extract fonts to /usr/local/share/fonts
  unarchive:
    src: usr/local/share/fonts.tar.gz
    dest: "/usr/local/share/fonts"
  when: fontsdir.changed
  ignore_errors: "{{ ansible_check_mode }}"

# - name: Install fonts.conf
#   copy:
#     src: home/.config/fontconfig/fonts.conf
#     dest: "{{ user.home }}/.config/fontconfig/fonts.conf"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: '0644'
#     backup: yes
#   tags: ['fonts']
#
- name: Update font-cache
  command: fc-cache -fv
  register: font_cache
  changed_when: font_cache.rc != 0
