---
# tasks file for desktop
- name: Collect only selected facts
  setup:
    filter:
      - 'ansible_processor'

- name: Theme Tasks
  debug:
    msg: "Starting theme tasks!"

- import_tasks:
    file: packages.yml
  tags: ['packages']

- name: Ensure theme directories exist
  file:
    dest: "{{ theme_directory_default_location }}/{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(theme_directory_default_owner) }}"
    group: "{{ item.group | default(theme_directory_default_group) }}"
    mode: "{{ item.mode | default(theme_directory_default_mode) }}"
    recurse: "{{ item.recurse | default(theme_directory_default_recurse) }}"
  with_items: "{{ theme_directory_definitions }}"
  check_mode: no
  tags: ['profile']

- block:
    - name: Copy theme package to temp
      copy:
        src: usr/local/share/themes/syncopated-theme-1.0-6-x86_64.pkg.tar.zst
        dest: /tmp/syncopated-theme-1.0-6-x86_64.pkg.tar.zst
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install syncopated theme
      pacman:
        name: /tmp/syncopated-theme-1.0-6-x86_64.pkg.tar.zst
        state: present
        extra_args: --overwrite '*'
      ignore_errors: "{{ ansible_check_mode }}"

  when: ansible_os_family == 'Archlinux'
  tags: ['packages']



# - import_tasks:
#     file: fonts.yml
#   tags: ['fonts']
#
# - import_tasks:
#     file: icons.yml
#   tags: ['icons']
#
# - name: Ensure /usr/local/share themes exists
#   file:
#     path: /usr/local/share/themes
#     state: directory
#     owner: root
#     group: root
#     recurse: True
#   register: themesdir
#
# - name: Extract themes into /usr/local/share/themes
#   unarchive:
#     src: "usr/local/share/themes/{{ item }}"
#     dest: "/usr/local/share/themes"
#   with_items:
#    - oomox-soundbot.tar.xz
#    - ArchLabs-Dark.tar.gz
#    - ArchLabs-Light.tar.gz
#   ignore_errors: "{{ ansible_check_mode }}"
#   when: themesdir.changed


- name: Install gtk 2 configurations
  copy:
    content: |
      # DO NOT EDIT! This file will be overwritten by LXAppearance.
      # Any customization should be done in ~/.gtkrc-2.0.mine instead.
      gtk-theme-name="{{ gtk.theme.name }}"
      gtk-icon-theme-name="{{ gtk.theme.icons }}"
      gtk-font-name="{{ font.primary.name }} {{ font.primary.size }}"
      gtk-cursor-theme-name="{{ gtk.theme.cursor }}"
      gtk-cursor-theme-size=0
      gtk-toolbar-style=GTK_TOOLBAR_BOTH
      gtk-toolbar-icon-size=GTK_ICON_SIZE_MENU
      gtk-button-images=1
      gtk-menu-images=1
      gtk-enable-event-sounds=1
      gtk-enable-input-feedback-sounds=1
      gtk-xft-antialias=1
      gtk-xft-hinting=1
      gtk-xft-hintstyle="hintfull"
      gtk-xft-rgba="rgb"
    dest: "{{ user.home }}/.gtkrc-2.0"
    owner: "{{ user.name }}"
    mode: '0644'

- name: Install gtk 3 and 4 configurations
  template:
    src: "{{ item }}.j2"
    dest: "{{ user.home }}/.config/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - 'gtk-3.0/bookmarks'
    - 'gtk-3.0/gtk.css'
    - 'gtk-3.0/settings.ini'
    - 'gtk-4.0/settings.ini'
  tags: ['profile', 'gtk']

- name: Install qt 5 and 6 configurations
  template:
    src: "{{ item }}.j2"
    dest: "{{ user.home }}/.config/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - 'Kvantum/kvantum.kvconfig'
    - 'qt5ct/colors/syncopated.conf'
    - 'qt5ct/qt5ct.conf'
    - 'qt6ct/colors/syncopated.conf'
    - 'qt6ct/qt6ct.conf'
  tags: ['profile', 'qt']

- name: Create syncopated backgrounds folder
  file:
    path: /usr/share/backgrounds/syncopated
    state: directory
    mode: '0755'
    group: "{{ user.group }}"

- name: Install backgrounds
  synchronize:
    src: "usr/share/backgrounds/syncopated/"
    dest: "/usr/share/backgrounds/syncopated/"
    recursive: yes
    mode: push
    delete: no
    rsync_opts:
      - "--update"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: ['backgrounds']
