---

- name: Current packages installed
  shell: |
    paru -Q |awk '{print $1}'
  become: False
  register: arch_installed_packages
  check_mode: no
  tags: ['always']

- name: arch_installed_packages
  set_fact:
    installed_packages: "{{ arch_installed_packages.stdout }}"
  tags: ['always']

- block:
    - name: Install Base packages
      aur:
        use: paru
        name: "{{ base_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Desktop packages
      aur:
        use: paru
        name: "{{ desktop_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Docker packages
      aur:
        use: paru
        name: "{{ desktop_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Theme packages
      aur:
        use: paru
        name: "{{ theme_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Tuning packages
      aur:
        use: paru
        name: "{{ tuning_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install X11 packages
      aur:
        use: paru
        name: "{{ x11_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"
      tags: ['x11_packages']

    - name: Install DAW packages
      aur:
        use: paru
        name: "{{ daw_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False

- block:
    - name: Install host specific xorg packages
      aur:
        use: paru
        name: "{{ host.xorg.video|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"
      when: host.xorg.video is defined

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False
  tags: ['x11_packages']
