authors:
- Robert Pannick <rwpannick@gmail.com>
dependencies: {}
description: Media creation and system interaction roles
license:
- MIT
name: media_tools
namespace: b08x
readme: README.md
repository: https://github.com/b08x/ansible-collections
tags:
- media tools
version: 1.0.0
