---
# tasks file for libvirt

- name: Libvirt Tasks
  ansible.builtin.debug:
    msg: "Starting libvirt tasks"

- block:
    # :: exfatprogs and exfat-utils are in conflict. Remove exfat-utils? [y/N]
    - name: Remove conflicting packages
      community.general.pacman:
        name: exfat-utils
        state: absent
        force: true
        extra_args: --noconfirm

    - name: Install libvirt packages
      pacman:
        name: "{{ item }}"
        state: present
        force: yes
        extra_args: --noconfirm --overwrite '*'
      loop:
        - dmidecode
        - dnsmasq
        - edk2-ovmf
        - libguestfs
        - libvirt
        - qemu-full
        - virt-install
        - virt-manager
        - virt-viewer

  when: ansible_os_family == 'Archlinux'
  tags: ['packages']

- name: Install Libvirt packages
  become: true
  when: use_libvirt | default(false) | bool
  ansible.builtin.package:
    name: "{{ libvirt_packages[ansible_distribution | lower] }}"
    state: present

- name: Set socket group and perms to allow for remote access
  ansible.builtin.copy:
    src: etc/libvirt/libvirtd.conf
    dest: /etc/libvirt/libvirtd.conf
    mode: '0644'

- name: Disable lvmetad for remote access reasons
  ansible.builtin.lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: "^    use_lvmetad = 1"
    line: "    use_lvmetad = 0"
    backrefs: true
    backup: true

- name: Add user to libvirt group
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "libvirt,kvm"
    append: true

- name: set libvirtd service preset
  when: libvirt.service == 'enabled'
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true

- when: use_vagrant|default(false)|bool == True
  tags:
  - vagrant
  ansible.builtin.import_tasks:
    file: vagrant.yml
