authors:
- Robert Pannick <rwpannick@gmail.com>
dependencies: {}
description: Desktop environment and window manager roles
license:
- MIT
name: desktop_environment
namespace: b08x
readme: README.md
repository: https://github.com/b08x/ansible-collections
tags:
- desktop environment
version: 1.0.9
