---
# tasks file for user

- name: User Tasks
  debug:
    msg: "Starting user tasks"

- name: Add user to groups
  user:
    name: "{{ user.name }}"
    groups: "video,audio,input"
    append: yes
  tags: ['groups']


- block:
    - name: Check if keys are present
      stat:
        path: "{{ user.home }}/.ssh/id_ed25519"
      register: keys

    - name: Start ssh daemon
      service:
        name: sshd
        state: started
        enabled: True

    - name: Copy keys from remote host
      delegate_to: 127.0.0.1
      run_once: True
      become_user: "{{ user.name }}"
      shell: "scp {{ user.name }}@{{ keyserver }}:~/.ssh/{{ item }} {{ user.home }}/.ssh/{{ item }}"
      args:
        chdir: "{{ user.home }}"
      with_items:
        - id_ed25519
        - id_ed25519.pub
        - id_rsa
        - id_rsa.pub
        - config
        - known_hosts
        - authorized_keys
      when:
        - not keys.stat.exists
        - newInstall is defined

  tags: ["keys"]


# dotfiles
# user defined tasks here
# - name: Install .gitconfig
#   template:
#     src: home/.gitconfig
#     dest: "{{ user.home }}/.gitconfig"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: '0644'
#   tags: ['dots']
