---

- name: Ensure input-remapper config directories exist
  file:
    dest: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.owner }}"
    group: "{{ user.group }}"
    mode: '0744'
    recurse: false
  loop:
    - ".config/input-remapper-2"
    - ".config/input-remapper-2/presets"
  check_mode: no
  tags: ['profile']

- name: Sync input-remapper presets folder
  synchronize:
    src: presets/
    dest: "{{ user.home }}/.config/input-remapper-2/presets/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
      - "--progress"
      - "--itemize-changes"
      - "--chown={{ user.name }}:{{ user.group }}"
