---
# Default variables for IDE role

# VSCode settings
vscode_extensions_enabled: true
vscode_user_settings_enabled: true

# Pulsar settings
pulsar_appimage_path: /usr/local/bin/pulsar
pulsar_desktop_entry_path: /usr/share/applications/pulsar.desktop
pulsar_icon_path: /usr/share/icons/hicolor/1024x1024/apps/pulsar.png
