---

- name: Install application packages
  block:
    - name: Install Debian packages
      apt:
        name: "{{ applications_packages.debian }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Fedora packages
      dnf:
        name: "{{ applications_packages.fedora }}"
        state: present
      when: ansible_distribution == "Fedora"

  rescue:
    - name: Handle package installation failures
      debug:
        msg: "Failed to install some packages. Please check the error message above."

- name: Install packages from alternative sources
  block:
    # Debian/Ubuntu specific tasks
    - name: Add Google Chrome repository key (Debian)
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Google Chrome repository (Debian)
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Google Chrome (Debian)
      apt:
        name: google-chrome-stable
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Timeshift PPA (Ubuntu)
      apt_repository:
        repo: ppa:teejee2008/timeshift
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Timeshift (Debian/Ubuntu)
      apt:
        name: timeshift
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # Fedora specific tasks
    - name: Install Fedora workstation repositories
      dnf:
        name: fedora-workstation-repositories
        state: present
      when: ansible_distribution == "Fedora"

    - name: Enable Google Chrome repository (Fedora)
      command: dnf config-manager --set-enabled google-chrome
      changed_when: false
      when: ansible_distribution == "Fedora"

    - name: Install Google Chrome (Fedora)
      dnf:
        name: google-chrome-stable
        state: present
      when: ansible_distribution == "Fedora"

    - name: Install Timeshift (Fedora)
      shell: |
        dnf copr enable -y frankcrawford/timeshift
        dnf install -y timeshift
      when: ansible_distribution == "Fedora"
