---

- name: Set teiler profiles
  copy:
    src: teiler
    dest: "{{ user.home }}/.config/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    backup: false

- name: Set teiler config
  template:
    src: teiler/config.j2
    dest: "{{ user.home }}/.config/teiler/config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: false
