---

- name: Install dracut
  ansible.builtin.package:
    name: dracut
    state: present

- name: Install additional dracut modules
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - dracut-network
    - dracut-live
  when: install_additional_modules | default(false)


- name: Create dracut configuration directory
  ansible.builtin.file:
    path: /etc/dracut.conf.d
    state: directory
    mode: '0755'

- name: Configure dracut
  ansible.builtin.template:
    src: etc/dracut.conf.j2
    dest: /etc/dracut.conf.d/custom.conf
    mode: '0644'
  register: config_dracut

- name: Rebuild initramfs
  ansible.builtin.command:
    cmd: dracut -f
  when: config_dracut.changed

# - name: Ensure dracut-regenerate-initramfs.service is enabled
#   ansible.builtin.systemd:
#     name: dracut-regenerate-initramfs.service
#     enabled: yes
#     state: started
