---

- name: Check if mirrors have been updated within the past 24h
  register: mirror_status
  tags:
  - mirrors
  ansible.builtin.shell: "fd --changed-within 24hours --search-path=/etc/pacman.d"

- name: Print mirror file status
  when:
  - ( mirror_status.stdout_lines | length < 0 or update_mirrors is defined )
  - debugging is defined
  tags:
  - mirrors
  ansible.builtin.debug:
    msg: "{{ mirror_status }}"
