---

- name: Current packages installed
  become: false
  register: arch_installed_packages
  check_mode: false
  tags:
  - always
  ansible.builtin.shell: |
    paru -Q |awk '{print $1}'

- name: arch_installed_packages
  tags:
  - always
  ansible.builtin.set_fact:
    installed_packages: "{{ arch_installed_packages.stdout }}"

- block:
    - name: Install Base packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ base_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Desktop packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ desktop_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Docker packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ desktop_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Theme packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ theme_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install Tuning packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ tuning_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install X11 packages
      tags:
      - x11_packages
      kewlfft.aur.aur:
        use: paru
        name: "{{ x11_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

    - name: Install DAW packages
      aur:
        use: paru
        name: "{{ daw_packages|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False

- block:
    - name: Install host specific xorg packages
      aur:
        use: paru
        name: "{{ host.xorg.video|difference(installed_packages) }}"
        state: present
        extra_args: "--overwrite '*'"
      when: host.xorg.video is defined

  rescue:
    - name: Handle installation failure
      debug:
        msg: "Failed to install a package. Check the logs."

  always:
    - name: Continue executions
      debug:
        msg: "Continuing with playbook execution."

  become: False
  tags: ['x11_packages']
