---

- name: Check if paru installed
  register: paru
  tags:
  - packages
  ansible.builtin.stat:
    path: /usr/bin/paru

- name: Install paru if not installed
  block:
    - name: Install paru
      pacman:
        name: paru
        state: present
        force: yes
        extra_args: --noconfirm
      register: paru_package
      until: "paru_package is not failed"
      retries: 2
      delay: 10

  rescue:
    - name: Clone paru
      become: false
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/paru.git"
        dest: "/tmp/paru"
        accept_hostkey: true
        update: true
        force: false

    - name: Make and install paru
      args:
        chdir: /tmp/paru
      become: false
      ansible.builtin.shell: "makepkg -si --noconfirm --needed"

    - name: clean and update package cache
      shell: "paru -Sc --noconfirm && paru -Syy"
      become: False

  when: not paru.stat.exists
  tags: ['packages']

- name: Adjust paru config
  ansible.builtin.template:
    src: etc/paru.conf.j2
    dest: /etc/paru.conf
    mode: '0644'
    backup: true
  # ignore_errors: "{{ ansible_check_mode }}"
