---

- name: Ensure input-remapper preset synchronization
  block:
    - name: Check presets source directory exists
      ansible.builtin.stat:
        path: presets/
      register: source_dir
      delegate_to: localhost

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: '{{ user.home }}/.config/input-remapper-2/presets/'
        state: directory
        mode: '0755'
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
      when: source_dir.stat.exists

    - name: Sync input-remapper presets folder
      ansible.posix.synchronize:
        checksum: true
        delete: false
        dest: '{{ user.home }}/.config/input-remapper-2/presets/'
        mode: push
        perms: false
        recursive: true
        rsync_opts:
          - --compress
          - --update
          - --omit-dir-times
          - --progress
          - --itemize-changes
          - --chown={{ user.name }}:{{ user.group }}
        src: presets/
      when: source_dir.stat.exists
      register: sync_result

  rescue:
    - name: Handle synchronization failure
      ansible.builtin.debug:
        msg: "Failed to sync input-remapper presets: {{ ansible_failed_result }}"