---

- block:
    - name: Enable tuned service
      register: tuned_service
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.systemd:
        name: tuned
        enabled: true
        state: started

    - name: Print tuned_service output
      when: debug is defined
      ansible.builtin.debug:
        msg: "{{ tuned_service }}"

    - name: Install realtime-modified profile
      ansible.builtin.copy:
        src: etc/tuned/realtime-modified/tuned.conf
        dest: /etc/tuned/realtime-modified/tuned.conf
        owner: root
        group: root
        mode: '0644'

    - name: Show tuned_service variable
      ignore_errors: true
      ansible.builtin.debug:
        msg: "{{ tuned_profile }}"

    - name: Set tuned profile
      shell: |
        tuned-adm profile {{ tuned.profile }}
      register: tuned_profile
      changed_when: tuned_profile.rc != 0
      when: tuned_service.state == 'started'
      ignore_errors: "{{ ansible_check_mode }}"

  tags: ['tuned']
