---
# tasks file for roles/distro
# at this point, packages will be set as a variable....

- setup:
- tags:
  - always
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}"

- name: Load a variable file based on the OS type, or a default if not found. the file.
  vars:
    params:
      files:
      - '{{ansible_os_family}}.yml'
      paths:
      - vars
  tags:
  - always
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"




- block:
    - import_tasks:
        file: "Archlinux/main.yml"
      tags: ['repo', 'mirrors']

    # - name: Current packages installed
    #   shell: |
    #     paru -Q |awk '{print $1}'
    #   become: False
    #   register: installed_packages
    #   check_mode: no
    #   tags: ['packages']
    #
    # - name: Set packages to be installed
    #   set_fact:
    #     arch_packages: "{{ packages|difference(arch_installed_packages.stdout) }}"
    #   check_mode: no
    #   tags: ['packages']

  when: ansible_os_family == 'Archlinux'

- block:
    - import_tasks:
        file: "RedHat/main.yml"
      tags: ['repo', 'dnf']

  when: ansible_os_family == 'RedHat'

- block:
    - import_tasks:
        file: "Debian/main.yml"
      tags: ['repo', 'apt']

  when: ansible_os_family == 'Debian'
  
