authors:
- Robert Pannick <rwpannick@gmail.com>
dependencies: {}
description: Development environment setup roles
license:
- MIT
name: development_tools
namespace: b08x
readme: README.md
repository: https://github.com/b08x/ansible-collections
tags:
- development tools
version: 1.0.5
