---
# tasks file for tuning

- name: RT Tasks
  debug:
    msg: "Starting RT tasks"

- name: Collect only selected facts
  setup:
    filter:
    - 'ansible_system_vendor'

- name: Install Tuning packages
  block:
    - name: Install main Tuning packages
      package:
        name: "{{ tuning_packages[ansible_distribution | lower] }}"
        state: present
      when: ansible_distribution == "Fedora"
      

    # - name: Install additional Tuning packages
    #   package:
    #     name: "{{ additional_tuning_packages[ansible_distribution | lower] }}"
    #     state: present
    #
    # - name: Install optional Tuning packages
    #   package:
    #     name: "{{ optional_tuning_packages[ansible_distribution | lower] }}"
    #     state: present
    #   when: install_optional_tuning_packages | default(false) | bool


- name: Handle missing packages
  block:
    - name: Warn about missing rtirq on Fedora
      debug:
        msg: "rtirq is not available in Fedora repositories. Consider finding an alternative or installing from source."
      when: ansible_distribution == "Fedora"

    - name: Warn about missing bpftune on Fedora
      debug:
        msg: "bpftune is not available in Fedora repositories. Consider finding an alternative or installing from source."
      when: ansible_distribution == "Fedora"

  when: ansible_distribution == "Fedora"

- name: Ensure tuned profile directory exists
  file:
    path: /etc/tuned/realtime-modified
    state: directory
    mode: '0755'
  become: true

- name: Ensure utillity config folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/security/limits.d
    - /etc/sysctl.d
    - /etc/tuned/realtime-modified

- name: Ensure user belongs to audio group
  user:
    name: "{{ user.name }}"
    groups: "audio"
    append: yes

- name: Set rtprio, memlock and nice for audio group
  copy:
    content: |
      @audio  - rtprio  98
      @audio  - nice    -19
      @audio  - memlock unlimited
    dest: "/etc/security/limits.d/99-realtime.conf"
    mode: '0644'
    backup: True
  ignore_errors: "{{ ansible_check_mode }}"
  when: tune_for_realtime == True


# It is safe to have this file even if
# your hardware contains neither device
# source: https://gentoostudio.org/?page_id=420
- name: Set timer permissions in udev rules
  copy:
    content: |
      KERNEL=="rtc0", GROUP="audio"
      KERNEL=="hpet", GROUP="audio"
    dest: "/etc/udev/rules.d/40-timer-permissions.rules"
    mode: '0644'

- name: Set sysctl parameters
  copy:
    src: etc/sysctl.d/99-cachyos-settings.conf
    dest: /etc/sysctl.d/99-cachyos-settings.conf
    mode: '0644'
    backup: True
  tags: ['sysctl']

- import_tasks: cpupower.yml
- import_tasks: rtkit.yml
- import_tasks: tuned.yml
