---


- name: Install docker packages
  loop:
  - nvidia-container-toolkit
  - nvidia-docker-compose
  become: false
  when:
  - ansible_os_family == 'Archlinux'
  - nvidia is defined
  kewlfft.aur.aur:
    use: paru
    name: "{{ item }}"
    state: present
    extra_args: "--overwrite '*'"
