---


- block:
    - name: Ensure docker data directory exists
      ansible.builtin.file:
        path: "{{ docker.storage }}"
        state: directory
        owner: root
        group: root

    - name: Set docker storage location
      ignore_errors: "{{ ansible_check_mode }}"
      notify: reload systemd daemon
      ansible.builtin.lineinfile:
        path: "/usr/lib/systemd/system/docker.service"
        regexp: "^ExecStart=/usr/bin/dockerd"
        line: "ExecStart=/usr/bin/dockerd --data-root {{ docker.storage }} -H fd:// --containerd=/run/containerd/containerd.sock"
        insertafter: "[Service]"
        firstmatch: true
        backup: true
          # register: dockerstorage
          # failed_when: "not 'Destination /usr/lib/systemd/system/docker.service does not exist' in dockerstorage.msg"

- name: Create docker config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

# - name: Set docker daemon options
#   template:
#     src: etc/docker/daemon.json.j2
#     dest: /etc/docker/daemon.json
#     owner: root
#     mode: '0644'
#     backup: True

- name: Disable overlay redirect
  ansible.builtin.copy:
    content: |
      options overlay metacopy=off redirect_dir=off

    dest: "/etc/modprobe.d/disable-overlay-redirect-dir.conf"
    owner: root

- name: Set docker service preset
  ignore_errors: "{{ ansible_check_mode }}"
  # register: dockerservice
  # failed_when: "not 'Could not find the requested service' in dockerservice.msg"
  ansible.builtin.systemd:
    name: docker
    enabled: true
