---
# handlers file for pulseaudio

- name: restart pulseaudio
  systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  with_items:
    - pulseaudio.service
    - pulseaudio.socket
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  become_user: "{{ user.name }}"
  ignore_errors: "{{ ansible_check_mode }}"
