---

use_docker: True
use_libvirt: True

tuned_profile: powersave
# share:
#   nfs:
#     parent: "{{ user.home }}"
#     exports:
#       - LLMOS
#       - Recordings
#       - Workspace

# bind_share_exports: True

cpupower:
  governor: performance
  perf_bias: 0

terminal: "kitty"
terminal_alt: "alacritty"

dm: False
browser: "google-chrome-stable"

font:
  primary:
    name: Hack Nerd Font
    size: 14
    hintstyle: hintsfull
  glyphs:
    name: Font Awesome 6 Free Regular
  mono:
    name: Hack Nerd Font Mono

x:
  autostart:
    - bash ~/.screenlayout/tinybot.sh
    # - "jacktrip -s -n 4 -q auto -b 24 -D --udprt &"
i3:
  autostart:
    - "keepassxc"
    - "barrier"
    # - "tilda -g ~/.config/tilda/config_0"
    - "tilda -g ~/.config/tilda/config_1"
#    - "barriers -f --no-tray --debug INFO --name tinybot --disable-crypto --disable-client-cert-checking -c /home/b08x/.config/Debauchee/tinybot.conf --address :24800"
  tray_output: "primary"
  assignments: "default"
  workspaces:
    - "$ws1 output HDMI-1"
    - "$ws2 output DP-2"
    - "$ws3 output HDMI-1"
    - "$ws4 output DP-2"
    - "$ws5 output HDMI-1"
    - "$ws6 output DP-2"
    - "$ws7 output HDMI-1"
    - "$ws8 output DP-2"
    - "$ws9 output HDMI-1"
    - "$ws10 output DP-2"
  keybindings: "default"

# network_interfaces:
#   - device: eth0
#     type: ethernet
#     ifname: eth0
#     conn_name: eth0
#     mac: 68:1d:ef:2a:ac:47
#     ip4: 192.168.41.43/24
#     gw4: 192.168.41.1
#     dns4:
#       - 192.168.41.41
#       - 192.168.41.1
#     dns4_search: syncopated.net
#     autoconnect: True
#     state: present
#     method4: manual
#   - device: eth1
#     type: ethernet
#     ifname: eth1
#     conn_name: eth1
#     mac: 68:1d:ef:2a:b4:03
#     ip4: 192.168.36.2/24
#     autoconnect: True
#     state: present
#     method4: manual
#   - device: wlan0
#     type: wifi
#     ifname: wlan0
#     conn_name: wlan0
#     ssid: "invisiblemagic"
#     mac: c2:03:79:0d:7d:b3
#     autoconnect: False
#     state: present
#     method4: disabled

host:
  xorg:
    video:
      # intel:
      - intel-gpu-tools
      - intel-media-driver
      - intel-ucode
      - libva-intel-driver
      - libva-mesa-driver
      # - libvdpau-va-gl-i965
      - vulkan-headers
      - vulkan-icd-loader
      - vulkan-intel
      - xf86-video-intel
      # opengl:
      - libva-utils
      - libvdpau-va-gl
      - libva-mesa-driver
      - mesa
      - mesa-utils
      - mesa-vdpau
      - vdpauinfo
      # opencl:
      - opencl-clover-mesa
      - opencl-rusticl-mesa
