---

- name: Placeholder for /etc/environment
  ansible.builtin.copy:
    src: etc/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Set /etc/profile
  ansible.builtin.template:
    src: etc/profile.j2
    dest: /etc/profile
    owner: root
    group: root
    mode: '0644'
    backup: true
