---

- name: Base Tasks
  register: expected_value
  ansible.builtin.debug:
    msg: "Starting base tasks"

- tags:
  - distro
  ansible.builtin.import_tasks:
    file: distro/main.yml

- tags:
  - packages
  ansible.builtin.import_tasks:
    file: packages.yml

- name: Ensure root directories exist
  loop: "{{ root_directory_definitions }}"
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default(false) }}"

- tags:
  - sshd
  ansible.builtin.import_tasks:
    file: sshd.yml

- tags:
  - env
  - profile
  ansible.builtin.import_tasks:
    file: environment.yml

- tags:
  - grub
  ansible.builtin.import_tasks:
    file: grub.yml

- tags:
  - updatedb
  ansible.builtin.import_tasks:
    file: updatedb.yml

- tags:
  - ranger
  ansible.builtin.import_tasks:
    file: ranger.yml

# - import_tasks:
#     file: lnav.yml
#   tags: ['lnav']

# - import_tasks:
#     file: zram.yml
#   tags: ["zram"]

# - import_tasks:
#     file: autofs.yml
#   tags: ["autofs"]

# - import_tasks:
#     file: autologin.yml
#   tags: ['autologin']
#   when: autologin is defined
