---

- name: Install Base packages
  block:
    - name: Install Fedora Base packages
      with_items:
      - '{{ base_packages.fedora }}'
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present

    - name: Install Debian Base packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "{{ base_packages.debian }}"
      when: ansible_os_family == 'Debian'

  rescue:
    - name: Handle package installation failures
      ansible.builtin.debug:
        msg: "Failed to install some Base packages. Please check the error message above."
