---

- name: Install ranger configs
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
  - ranger
  ansible.posix.synchronize:
    src: etc/skel/.config/ranger/
    dest: "{{ user.home }}/.config/ranger/"
    recursive: true
    mode: push
    delete: false
    checksum: true
    perms: false
    rsync_opts:
    - --update
    - --omit-dir-times
    - --progress
    - --itemize-changes
    - --chown={{ user.name }}:{{ user.group }}
