---

- name: Copy Timeshift custom json
  ansible.builtin.copy:
    src: etc/timeshift/config.json
    dest: /etc/timeshift/config.json
    mode: '0644'
    owner: root
    group: root
    validate: /usr/bin/timeshift --check %s
