---

- name: Check if locate command is available
  register: locate_check
  ignore_errors: true
  ansible.builtin.command: locate --version

- name: Set locate_available variable
  ansible.builtin.set_fact:
    locate_available: "{{ not locate_check.failed }}"

- block:
    - name: Set directories to not be indexed
      register: updatedb_conf
      ansible.builtin.template:
        src: etc/updatedb.conf.j2
        dest: /etc/updatedb.conf
        owner: root
        group: root
        mode: '0644'
        backup: true

    - name: Run updatedb
      command: "updatedb"
      when: updatedb_conf.changed
      ignore_errors: True

  when: locate_available|bool
