---
- name: NAS Tasks
  ansible.builtin.debug:
    msg: "Starting NAS tasks"

- tags:
  - nfs
  ansible.builtin.import_tasks:
    file: nfs.yml

- when: samba_host|bool
  tags:
  - samba
  ansible.builtin.import_tasks:
    file: samba.yml

# - import_tasks:
#     file: rsyncd.yml
#   when: rsyncd_host|bool
#   tags: ['rsyncd']
#
# - import_tasks:
#     file: musikcube.yml
#   when: musikcube_host|bool
#   tags: ['musikcube']
