---

- hosts: all
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"

  pre_tasks:
    - name: Set datetime
      tags:
      - always
      ansible.builtin.set_fact:
        datetime: ansible_date_time.epoch

    - name: Set suffix
      set_fact:
        suffix: ".{{ ansible_date_time.epoch }}.{{ ansible_date_time.date }}@{{ ansible_date_time.time }}~"
      tags: ["always"]

  roles:

    - name: homepage
      import_role: homepage
      tags: ["homepage"]

  post_tasks:
    - name: Cleanup old backup files
      when: cleanup is defined
      tags:
      - cleanup
      ansible.builtin.script: "cleanup.sh"
