---

- name: setup build host
  hosts: localhost
  become: True
  gather_subset:
    - hardware
    - network
  vars_files:
    - ../vars/packager/user.yml
  vars:

    repository_urls:
      - http://syncopated.hopto.org/repo/
      - http://bender.syncopated.net/repo/

    path:
      - "{{ lookup('env','HOME') }}/.local/share/gem/ruby/3.0.0/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"

    environment:
      PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
      PKG_CONFIG_PATH: "/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"
      ZSH: "/usr/share/oh-my-zsh"
      DISPLAY: ":0"

  pre_tasks:

    - name: Set admin group name
      set_fact:
        admin_group: wheel
      tags: ['always']

    - name: set packager_workspace fact
      set_fact:
        packager_workspace: "{{ packager.workspace }}"


    - block:
        - name: check -march support
          shell: /lib/ld-linux-x86-64.so.2 --help | grep supported|xargs|awk '{print $1}'
          register: supported_march

        - name: check output from grep command
          debug:
            msg: "{{ supported_march }}"

        - name: set architecture
          set_fact:
            architecture: "x86-64-v3"
          when: supported_march.stdout_lines[0] == 'x86-64-v3'

        - name: set architecture
          set_fact:
            architecture: "x86-64"
          when: supported_march.stdout_lines[0] == 'x86-64-v2'

      ignore_errors: "{{ ansible_check_mode }}"
      tags: ['flags']

  roles:

    - role: pkgbuild
    # - role: rpm
