---
- hosts: llmops
  become: True
  gather_facts: yes
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:
  
    - name: Install and configure Docker
      import_role: docker
      when: use_docker == True
      tags: ["docker"]

    - name: Install and configure KVM
      import_role: libvirt
      when: use_libvirt == True
      tags: ["libvirt"]
