---
- hosts: workstation
  become: true
  gather_facts: true
  collections:
    - b08x.llmops_dev
    - b08x.system_core
    - b08x.shell_environment
    - b08x.development_tools
    - b08x.desktop_environment
    - b08x.media_tools
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.asdf/bin"
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/Utils/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"

  roles:

    - name: terminal
      import_role: terminal
      tags: ["terminal"]

    - name: theme
      import_role: theme
      tags: ["theme"]

    - name: i3
      import_role: i3
      when: desktop_environment == 'i3'
      tags: ["i3"]

    - name: gnome
      import_role: gnome
      when: desktop_environment == 'gnome'
      tags: ["gnome"]

    - name: barrier
      import_role: barrier
      tags: ["barrier"]

    - name: input-remapper
      import_role: input-remapper
      from: b08x.desktop_environment
      tags: ["input-remapper"]

    - name: applications
      import_role: applications
      tags: ["applications"]

    - name: obs-studio
      import_role: obs-studio
      tags: ["obs-studio"]

    - name: deadbeef
      import_role: deadbeef
      tags: ["deadbeef"]
