---
# # Add Docker's official GPG key:
# sudo apt-get update
# sudo apt-get install ca-certificates curl
# sudo install -m 0755 -d /etc/apt/keyrings
# sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
# sudo chmod a+r /etc/apt/keyrings/docker.asc
#
# # Add the repository to Apt sources:
# echo \
#   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
#   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update


- name: Update package lists
  apt: update_cache=yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 0444

- name: Add Docker repository
  copy:
    content: |
      deb [arch={{ ansible_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -sc) stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644

- name: Update package lists (again)
  apt: update_cache=yes
