---

- name: Check if TouchOSC is already installed
  stat:
    path: "/usr/local/bin/TouchOSC_{{ touchosc.version }}"
  register: touchosc_installed
  changed_when: false

- name: Check if update_TouchOSC variable is defined
  set_fact:
    touchosc_update_required: "{{ update_TouchOSC is defined }}"
  changed_when: false

- block:
    - name: Remove existing TouchOSC version
      file:
        path: "/usr/local/bin/TouchOSC_{{ touchosc.version }}"
        state: absent
      when: touchosc_installed.stat.exists and touchosc_update_required

    - name: Fetch TouchOSC
      get_url:
        url: "{{ touchosc.url }}/{{ touchosc.file }}"
        dest: "/tmp"

    - name: Extract and install TouchOSC
      shell:
        cmd: |
          unzip -q -o "/tmp/{{ touchosc.file }}" -d "/tmp"
          mv "/tmp/TouchOSC" "/usr/local/bin/TouchOSC_{{ touchosc.version }}"
          chmod +x /usr/local/bin/TouchOSC_{{ touchosc.version }}
      args:
        creates: "/usr/local/bin/TouchOSC_{{ touchosc.version }}"
        executable: /bin/bash

    - name: create new symlink
      file:
        src: "/usr/local/bin/TouchOSC_{{ touchosc.version }}"
        dest: "/usr/local/bin/TouchOSC"
        state: link
        force: yes

    - name: Install desktop entry
      copy:
        src: usr/share/applications/TouchOSC.desktop
        dest: /usr/share/applications/TouchOSC.desktop
        mode: '644'

  when: not touchosc_installed.stat.exists or touchosc_update_required
