---
# defaults file for jackd

# JACK role packages
jack_packages:
  archlinux:
    - jack2
    - jack2-dbus
    - jack-example-tools
    - jack-keyboard
    - jack_capture
    # - jack_link
    - jack_mixer
    - jack_snapshot
    - jack_utils
    - jacktrip
  fedora:
    - jack-audio-connection-kit
    - jack-audio-connection-kit-dbus
    # - jack-example-tools  # Not available in Fedora repos
    - jack-keyboard
    # - jack_capture  # Not available in Fedora repos
    # - jack_link  # Not available in Fedora repos
    # - jack_mixer  # Not available in Fedora repos
    # - jack_snapshot  # Not available in Fedora repos
    # - jack_utils  # Not available in Fedora repos
    # - jacktrip  # Not available in Fedora repos

jack_control:
  dps:
    device: hw:0
    capture: none
    playback: none
    rate: 48000
    period: 1024
    nperiods: 2
    hwmon: False
    hwmeter: False
    duplex: True
    softmode: False
    monitor: True
    dither: n
    shorts: False
    mididriver: seq
  eps:
    driver: alsa
    name: default
    realtime: True
    realtimepriority: 89
    temporary: False
    verbose: False
    # client-timeout: Client timeout limit in milliseconds. (sint:notset:0:0)
    # clock-source: Clocksource type : c(ycle) | h(pet) | s(ystem). (uint:notset:0:0)
    port-max: 2048
    replaceregistry: False
    sync: False
    # self-connect-mode: Self connect mode. (char:notset: : )
    # slave-drivers: Slave drivers to use (str:notset::)
