authors:
- Robert Pannick <rwpannick@gmail.com>
dependencies: {}
description: Audio system and DAW configuration roles
license:
- MIT
name: audio_production
namespace: b08x
readme: README.md
repository: https://github.com/b08x/ansible-collections
tags:
- audio production
version: 1.0.0
