---
# tasks file for ruby
- name: Ruby Tasks
  ansible.builtin.debug:
    msg: "Starting ruby tasks"

- name: Load a variable file based on the OS type, or a default if not found.
  vars:
    params:
      files:
      - '{{ansible_os_family}}.yml'
      paths:
      - vars
  tags:
  - packages
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"

- name: Load the main vars
  vars:
    params:
      paths:
      - vars
  ansible.builtin.include_vars: main.yml

- setup:
- ansible.builtin.debug:
    msg: "{{ packages }}"

# by default /etc/gemrc is set to --user-install
# set --no-user-install in /root/.gemrc
# to install gems system wide using sudo

- name: Set --no-user-install in /root/.gemrc
  ansible.builtin.copy:
    content: |
      gem: --no-user-install --no-document
    dest: "/root/.gemrc"
    owner: root

- name: Set --user-install in /home/user/.gemrc
  ansible.builtin.copy:
    content: |
      gem: --user-install
    dest: "{{ user.home }}/.gemrc"
    owner: "{{ user.name }}"

- name: Set --no-user-install in /etc/gemrc
  ansible.builtin.copy:
    content: |
      gem: --user-install
    dest: "/etc/gemrc"
    owner: root

- name: Install Ruby dev packages
  tags:
  - packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

# - import_tasks:
#     file: asdf.yml
#   tags: ['asdf']

# - name: Install ruby profile.d script
#   template:
#     src: etc/profile.d/ruby.sh.j2
#     dest: /etc/profile.d/ruby.sh
#     owner: root
#     group: root
#     mode: '0755'
#     backup: True

- name: update system bundler
  ansible.builtin.shell: gem update --system

- name: gather list of installed gems
  become: false
  register: gemlist
  changed_when: gemlist.rc != 0
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.shell: "gem list | awk '{ print $1 }'"

- name: set list of gems to install
  ansible.builtin.set_fact:
    ruby__gems: "{{ gems|difference(gemlist.stdout) }}"

- name: install ruby gems
  become: false
  with_items:
  - '{{ ruby__gems }}'
  when: ruby__gems | length > 0
  ansible.builtin.shell: "gem install {{ item }}"

- block:

    - name: Install RVM
      become: false
      ansible.builtin.import_tasks: 'rvm.yml'

    - name: Install Ruby and Gems
      import_tasks: 'rubies.yml'
      become: False

  when: rvm_install|default(false)|bool == True
  tags: ['rvm']
