---

- name: Detect rvm binary
  register: rvm_binary
  ansible.builtin.stat:
    path: "'{{ rvm1_rvm }}'"

- name: Detect rvm installer
  register: rvm_installer
  ansible.builtin.stat:
    path: "'{{ rvm1_temp_download_path }}/rvm-installer.sh'"

- name: Detect current rvm version
  changed_when: false
  register: rvm_current_version
  when: rvm_binary.stat.exists
  ansible.builtin.command: '{{ rvm1_rvm}} version'

- name: Install rvm installer
  when: not rvm_installer.stat.exists
  ansible.builtin.get_url:
    url: '{{ rvm1_rvm_latest_installer }}'
    dest: '{{ rvm1_temp_download_path }}/rvm-installer.sh'
    mode: 493

- block:

    - name: Import GPG keys from keyservers
      shell: 'gpg2 --batch --keyserver {{ item }} --recv-keys {{ rvm1_gpg_keys }}'
      changed_when: False
      check_mode: False
      with_items: '{{ rvm1_gpg_key_servers }}'

  rescue:

    - name: Import GPG keys from rvm.io, if keyservers failed
      shell: |
        gpg2 --keyserver keyserver.ubuntu.com --recv-keys \
        409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

  when: not rvm_binary.stat.exists

- name: Install rvm
  when: not rvm_binary.stat.exists
  ansible.builtin.shell: >
    /usr/bin/env bash {{ rvm1_temp_download_path }}/rvm-installer.sh {{ rvm1_rvm_version }}
    --path {{ rvm1_install_path }} {{ rvm1_install_flags }}

- name: Update rvm
  changed_when: false
  when: rvm_binary.stat.exists and rvm1_rvm_check_for_updates
  ansible.builtin.shell: '{{ rvm1_rvm }} get {{ rvm1_rvm_version }} && {{ rvm1_rvm }} reload'

- name: Configure rvm
  when: not rvm_binary.stat.exists
  ansible.builtin.command: '{{ rvm1_rvm }} autolibs {{ rvm1_autolib_mode }}'

- name: Detect rvm openssl
  register: rvm_openssl
  ansible.builtin.stat:
    path: "'{{ rvm1_install_path }}/usr/ssl'"

- name: Install openssl
  when:
  - not rvm_openssl.stat.exists
  ansible.builtin.command: '{{ rvm1_rvm }} pkg install openssl'
