#!/usr/bin/env ruby
# frozen_string_literal: true

BINDIR = File.expand_path(File.join(__dir__))
$LOAD_PATH.unshift(BINDIR) unless $LOAD_PATH.include?(BINDIR)

require "ohmannium"

require "pry"
Pry.start
